### ISSUE TITLE
PDF version of docs

### ISSUE THREAD

**Issue by dacap** [aseprite/docs#3]
Some users asked for a PDF version of the docs, we could try to convert markdown files to pdf using pandoc.

**Comment by stmio** [comment]
Hi @dacap 👋

I am currently working on a solution to this with a [pandoc GitHub Action](https://github.com/stmio/aseprite-docs/blob/md-to-pdf/.github/workflows/md-to-pdf.yml) that automatically converts all the markdown files into a PDF document after a commit has been made. The PDF is then stored in [GitHub Artifact storage](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) for 90 days, so it can be downloaded as a zip file and used elsewhere.

For most of the document, it works fine ([see here](https://github.com/stmio/aseprite-docs/actions/runs/4589046183)), although there are still a few issues that need fixing:
- The links to other files (e.g. the "See Also" sections at the bottom of pages) are not converted to PDF links, and there does not seem to be an easy way to do this automatically using pandoc
- Some unicode characters such as the Mac OS command key (⌘) are not displayed in the PDF, and I haven't had much success in changing the font used by pandoc inside the GitHub Action
- A few images are broken, especially in the Sprite Sheets section for some reason
- Occasionally, when viewing the PDF in Adobe Acrobat, error messages ("An error exists on this page") appear in seemingly random places
- The generated PDF document isn't looking _great_ by any means

I'll see if I can fix any of these over the next few weeks or so– in the meantime, are you aware of any fixes?

Thanks! 😃
