### ISSUE TITLE
Inconsistencies betweeen table of content and available pages.

### ISSUE THREAD

**Issue by T1mL3arn** [aseprite/docs#38]
1. go to https://www.aseprite.org/docs/
2. see this
![image](https://github.com/aseprite/docs/assets/9349164/13716d84-93ed-4c45-8ac8-a0df7930044c)

expected:  Table of content on the left is the same as main content.

**Comment by dacap** [comment]
Hi @T1mL3arn, thanks for the feedback. There are no plans to make the sidebar as verbose as the main content page. The idea of the sidebar is to have a quick overview of the main topics/sections.
