### ISSUE TITLE
A mistype

### ISSUE THREAD

**Issue by DTRW919** [aseprite/docs#5]
While looking at the docs FAQ page, I noticed that at [the bottom of the page](https://www.aseprite.org/faq/#how-do-i-update-my-current-version), where it says "It's a little "tribute" to what **we think it's the greatest game of all times: Super Mario World.** Specifically it references one of the few animated blocks of this game: [the rotating block.](https://www.mariowiki.com/Rotating_Block)". The bolded words, 'think it's' I think should be changed to 'think is'. Otherwise it would be like saying: "It's a little "tribute" to what we think it is the greatest game of all times: Super Mario World." Thanks for reading this, I'll continue reading the docs and post issues here! <3 (Also not sure about this one but in the same place, "times" I think should be time) **If you guys think that the docs are fine the way they are, please tell me and I'll stop, thanks again!**

**Comment by dacap** [comment]
Hi @DTRW919, thanks for your comments. I've just uploaded these fixes :+1:

**Comment by DTRW919** [comment]
One more thing, it's not in the docs so I thought it'd be more convenient to put it here, on the [home page](https://aseprite.org), where it showcases the Aseprite features, it says "Recovery your sprites in case of crash." under the Data Recovery tab, but it should probably be changed to "Recover your sprites in case of a crash", <3 Thanks for the very quick response!
